import type { Metadata } from "next";
import LegalPage from "../../../components/legal/LegalPage";
export const metadata: Metadata = { title: "Quy định cộng đồng", description: "Quy tắc đăng bài, bình luận, ảnh đính kèm và xử lý vi phạm tại TRIA Community." };
export default function CommunityRulesPage() { return <LegalPage eyebrow="Community · TRIA CAFE" title="Quy định cộng đồng" intro="TRIA Community là không gian chia sẻ kinh nghiệm cà phê. Mọi thành viên phải tôn trọng pháp luật, quyền riêng tư và quyền sở hữu trí tuệ của người khác." sections={[
 { title: "1. Nội dung được khuyến khích", paragraphs: ["Chia sẻ công thức, trải nghiệm máy/hạt, kiến thức vận hành quán, bảo dưỡng, workshop và câu hỏi có ích cho cộng đồng. Hãy đưa thông tin chính xác, nêu rõ trải nghiệm cá nhân và nguồn khi trích dẫn."] },
 { title: "2. Nội dung bị cấm", paragraphs: ["TRIA có quyền ẩn, chỉnh sửa, gỡ hoặc khóa tài khoản đối với nội dung vi phạm."], bullets: ["Nội dung trái pháp luật, kích động bạo lực, thù ghét, quấy rối, đe dọa hoặc xâm hại trẻ em.", "Mạo danh, lừa đảo, spam, quảng cáo không được phép, seeding giả hoặc thao túng vote/điểm.", "Tiết lộ dữ liệu cá nhân, số điện thoại, địa chỉ, hình ảnh của người khác khi chưa được đồng ý.", "Nội dung xâm phạm bản quyền, nhãn hiệu, bí mật kinh doanh hoặc sử dụng ảnh không có quyền.", "Thông tin y tế, tài chính, pháp lý nguy hiểm được trình bày như cam kết chuyên môn."] },
 { title: "3. Ảnh và file đính kèm", paragraphs: ["Bạn chỉ được tải ảnh/file mà bạn có quyền sử dụng và không chứa dữ liệu nhạy cảm của người khác. File upload hiện giới hạn tối đa 5MB mỗi ảnh; TRIA có thể xóa file nguy hiểm, vi phạm hoặc gây rủi ro bảo mật."] },
 { title: "4. Báo cáo và xử lý", paragraphs: ["Gửi báo cáo tới hello@triacafe.vn với URL bài viết/bình luận, lý do và bằng chứng. TRIA sẽ ưu tiên xử lý nội dung nguy hiểm, xâm phạm trẻ em, lừa đảo hoặc vi phạm dữ liệu cá nhân. Trong trường hợp cần thiết, TRIA có thể phối hợp với cơ quan có thẩm quyền."] },
 { title: "5. Quyền với nội dung thành viên", paragraphs: ["Bạn giữ quyền đối với nội dung do mình tạo nhưng cấp cho TRIA quyền không độc quyền để lưu trữ, hiển thị và phân phối nội dung đó nhằm vận hành Community. Bạn cam kết có đủ quyền và chịu trách nhiệm với nội dung đã đăng."] },
]} />; }
