import { badgeFor } from "./types";
import type { CommunityPost } from "./types";

const avatar = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&q=80&w=150`;
const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&q=80&w=900`;

/**
 * Sample content shown before the API responds (or when the DB is empty),
 * so the community page is never blank for a first-time visitor.
 */
export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "post-1",
    title: "Cách căn chỉnh độ mịn hạt Robusta Cầu Đất cho máy pha Espresso 1 Group không bị chua",
    content: "Với Fine Robusta mật độ cao, mình bắt đầu ở 18g dose, yield 40g trong 27-30 giây. Nếu shot chua và dòng chảy nhanh, giảm cỡ xay từng nấc nhỏ trước khi tăng nhiệt. Hãy ghi lại mỗi thay đổi để tìm đúng điểm cân bằng.",
    author: { id: "sample-1", name: "Hoàng Barista", image: avatar("photo-1534528741775-53994a69daeb"), role: "TRIA_BARISTA", badge: "TRIA Master Barista" },
    category: "home-barista",
    categoryLabel: "Góc Home Barista",
    tags: ["#DialIn", "#FineRobusta"],
    status: "Đã giải đáp",
    time: "2 giờ trước",
    upvotes: 128,
    downvotes: 2,
    comments: 24,
    views: 1830,
    points: 45,
    image: image("photo-1447933601403-0c6688de566e"),
    commentsData: [{ id: "c1", author: "Linh Nguyễn", avatar: avatar("photo-1494790108377-be9c29b29330"), badge: badgeFor("Home Barista"), body: "Tỷ lệ 1:2.2 rất hợp với hạt này, cảm ơn anh đã chia sẻ.", time: "1 giờ trước" }],
  },
  {
    id: "post-2",
    title: "[Bắt bệnh] Máy pha bị tụt áp suất giữa chừng và tiếng bơm kêu to",
    content: "Hãy tắt máy, xả áp và kiểm tra lần lượt nguồn nước, van cấp, lưới lọc và bơm. Không tự tháo nồi hơi khi máy còn nóng. Nếu tiếng bơm vẫn lớn sau khi mồi nước, gửi video và mã máy để kỹ thuật viên TRIA hỗ trợ.",
    author: { id: "sample-2", name: "Kỹ thuật viên Tuấn", image: avatar("photo-1507003211169-0a1dd7228f2d"), role: "TRIA_TECH", badge: "TRIA Tech Specialist" },
    category: "machine-tech",
    categoryLabel: "Bắt bệnh máy pha",
    tags: ["#GiaiCuuBarista", "#SuaMay"],
    status: "Cần kỹ thuật TRIA",
    time: "5 giờ trước",
    upvotes: 96,
    downvotes: 1,
    comments: 31,
    views: 2410,
    points: 60,
    image: image("photo-1517668808822-9ebb02f2a0e6"),
    commentsData: [{ id: "c2", author: "Kỹ thuật TRIA", avatar: avatar("photo-1560250097-0b93528c311a"), badge: badgeFor("TRIA Tech Specialist"), body: "Đã đánh dấu giải pháp chuẩn. Bạn kiểm tra van một chiều trước nhé.", time: "4 giờ trước", accepted: true }],
  },
  {
    id: "post-3",
    title: "Bài toán Cost 1 ly Latte cho quán cà phê diện tích 30m2 tại Quận 1",
    content: "Với 18g cà phê, 180ml sữa và bao bì, tổng cost nguyên liệu của một ly Latte là khoảng 11.800đ. Điều quan trọng là cố định recipe, cân định lượng mỗi ca và theo dõi hao hụt sữa.",
    author: { id: "sample-3", name: "Minh Đức", image: avatar("photo-1500648767791-00dcc994a43e"), role: "CAFE_OWNER", badge: "Cafe Owner" },
    category: "cafe-owner",
    categoryLabel: "Thực chiến quản lý quán",
    tags: ["#CostLy", "#VanHanhQuan"],
    status: "Bài chia sẻ",
    time: "1 ngày trước",
    upvotes: 112,
    downvotes: 3,
    comments: 56,
    views: 3270,
    points: 80,
    commentsData: [],
  },
  {
    id: "post-4",
    title: "Cupping Notes: TRIA Signature Blend và hậu vị caramel của vụ mới",
    content: "Mẻ blend lần này có body dày và crema ổn định. Ở espresso, note chocolate nổi bật; pour-over cho hậu vị caramel rõ hơn. Đây là lựa chọn tốt cho menu sữa và cold brew.",
    author: { id: "sample-4", name: "Mai Anh", image: avatar("photo-1544005313-94ddf0286df2"), role: "MEMBER", badge: "Home Barista" },
    category: "tria-lab",
    categoryLabel: "TRIA Lab & Review hạt",
    tags: ["#TriaTester", "#Cupping"],
    status: "Review sản phẩm",
    time: "1 ngày trước",
    upvotes: 74,
    downvotes: 0,
    comments: 19,
    views: 1540,
    points: 35,
    image: image("photo-1495474472287-4d71bcdd2085"),
    commentsData: [],
  },
  {
    id: "post-5",
    title: "Mời tham gia Workshop Cupping Fine Robusta sáng Thứ 7 tại TRIA Flagship Q.3",
    content: "Workshop diễn ra lúc 09:00 sáng Thứ 7 tại TRIA Flagship Q.3. Số lượng giới hạn 18 người, ưu tiên thành viên Community đăng ký sớm.",
    author: { id: "sample-5", name: "TRIA Community Team", image: avatar("photo-1551836022-d5d88e9218df"), role: "TRIA_BARISTA", badge: "TRIA Master Barista" },
    category: "events",
    categoryLabel: "Workshop & Sự kiện",
    tags: ["#WorkshopTRIA", "#HCMC"],
    status: "Mở đăng ký",
    time: "2 ngày trước",
    upvotes: 86,
    downvotes: 0,
    comments: 12,
    views: 2100,
    points: 25,
    image: image("photo-1554118811-1e0d58224f24"),
    commentsData: [],
  },
  {
    id: "post-6",
    title: "Vệ sinh group head mỗi ngày: checklist 5 phút cho quán đông khách",
    content: "Cuối mỗi ca, chạy backflush nước, chải group head, lau shower screen và vệ sinh vòi steam ngay sau khi dùng. Mỗi tuần nên dùng bột vệ sinh theo hướng dẫn của nhà sản xuất.",
    author: { id: "sample-6", name: "Ngọc Trâm", image: avatar("photo-1488426862026-3ee34a7d66df"), role: "MEMBER", badge: "Newbie Brewer" },
    category: "machine-tech",
    categoryLabel: "Bắt bệnh máy pha",
    tags: ["#BaoDuong", "#BarWorkflow"],
    status: "Hướng dẫn",
    time: "3 ngày trước",
    upvotes: 61,
    downvotes: 1,
    comments: 11,
    views: 920,
    points: 20,
    commentsData: [],
  },
  {
    id: "post-7",
    title: "Pour-over Fine Robusta: nên dùng nhiệt độ bao nhiêu để vị không gắt?",
    content: "Ở 92 độ C, ly có sweetness cân bằng nhất. Giảm nhiệt nếu hậu vị khô; tăng nhẹ nhiệt hoặc kéo dài thời gian bloom nếu ly mỏng và thiếu body.",
    author: { id: "sample-7", name: "Quốc Bảo", image: avatar("photo-1506794778202-cad84cf45f1d"), role: "MEMBER", badge: "Home Barista" },
    category: "home-barista",
    categoryLabel: "Góc Home Barista",
    tags: ["#PourOver", "#Recipe"],
    status: "Thảo luận",
    time: "4 ngày trước",
    upvotes: 49,
    downvotes: 0,
    comments: 15,
    views: 880,
    points: 18,
    commentsData: [],
  },
  {
    id: "post-8",
    title: "Chọn máy pha 2 Group cho quán 80 ly/ngày: bài toán đầu tư và bảo trì",
    content: "Nếu lưu lượng ổn định trên 60 ly/ngày, máy 2 Group giúp giảm thời gian chờ và giữ nhiệt tốt hơn. Hãy tính cả chi phí lọc nước, bảo trì định kỳ và training barista vào ngân sách.",
    author: { id: "sample-8", name: "Phúc Lê", image: avatar("photo-1507591064344-4c6ce005b128"), role: "CAFE_OWNER", badge: "Cafe Owner" },
    category: "cafe-owner",
    categoryLabel: "Thực chiến quản lý quán",
    tags: ["#B2B", "#May2Group"],
    status: "B2B Choice",
    time: "5 ngày trước",
    upvotes: 88,
    downvotes: 2,
    comments: 28,
    views: 1940,
    points: 55,
    commentsData: [],
  },
];