"use client";

import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Search, Trash2 } from "lucide-react";
import { deleteUser, updateUserRole } from "../../app/actions/admin";

const roles = ["MEMBER", "CAFE_OWNER", "TRIA_BARISTA", "TRIA_TECH", "ADMIN"] as const;
type UserRow = { id: string; name: string | null; email: string | null; role: typeof roles[number]; badge: string; triaPoints: number; createdAt: string };
export default function UserManager() {
  const [items, setItems] = useState<UserRow[]>([]); const [q, setQ] = useState(""); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1);
  async function load() { const response = await fetch(`/api/admin/users?page=${page}&pageSize=10&q=${encodeURIComponent(q)}`, { cache: "no-store" }); const data = await response.json(); if (response.ok) { setItems(data.items); setTotalPages(data.totalPages); } }
  useEffect(() => { void load(); }, [page, q]);
  async function changeRole(user: UserRow, role: string) { await updateUserRole(user.id, role as typeof roles[number]); await load(); }
  async function remove(user: UserRow) { if (!window.confirm(`XÃ³a tÃ i khoáº£n ${user.email || user.name}?`)) return; try { await deleteUser(user.id); await load(); } catch (error) { window.alert(error instanceof Error ? error.message : "KhÃ´ng thá»ƒ xÃ³a user."); } }
  return <section className="overflow-hidden rounded-2xl border border-[#3A302B] bg-[#171412]"><div className="border-b border-[#2A2421] p-5"><h2 className="text-xl font-bold text-white">Quáº£n lÃ½ ngÆ°á»i dÃ¹ng</h2><p className="mt-1 text-xs text-[#81746B]">TÃ¬m kiáº¿m, Ä‘á»•i role, theo dÃµi badge/points vÃ  xÃ³a user.</p></div><div className="border-b border-[#2A2421] p-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#81746B]" /><input value={q} onChange={(e) => { setPage(1); setQ(e.target.value); }} placeholder="TÃ¬m tÃªn hoáº·c email..." className="w-full rounded-xl border border-[#3A302B] bg-[#221D1A] py-2.5 pl-10 text-sm text-white outline-none focus:border-[#D97706]" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#221D1A] text-xs uppercase text-[#A69B93]"><tr><th className="px-5 py-3">NgÆ°á»i dÃ¹ng</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Badge / Points</th><th className="px-5 py-3">Thao tÃ¡c</th></tr></thead><tbody>{items.map((user) => <tr key={user.id} className="border-t border-[#2A2421]"><td className="px-5 py-4"><strong className="text-white">{user.name || "ChÆ°a Ä‘áº·t tÃªn"}</strong><span className="block text-xs text-[#81746B]">{user.email}</span></td><td className="px-5 py-4"><select value={user.role} onChange={(e) => void changeRole(user, e.target.value)} className="rounded-lg border border-[#3A302B] bg-[#221D1A] px-2 py-2 text-xs text-white"><option value="MEMBER">MEMBER</option><option value="CAFE_OWNER">CAFE_OWNER</option><option value="TRIA_BARISTA">TRIA_BARISTA</option><option value="TRIA_TECH">TRIA_TECH</option><option value="ADMIN">ADMIN</option></select></td><td className="px-5 py-4 text-xs text-[#CDBBAA]">{user.badge}<br /><span className="text-[#F0B429]">{user.triaPoints} points</span></td><td className="px-5 py-4"><button type="button" aria-label="XÃ³a user" onClick={() => void remove(user)} className="rounded-lg border border-red-900/50 p-2 text-red-400"><Trash2 className="h-4 w-4" /></button></td></tr>)}</tbody></table></div>{!items.length && <p className="p-8 text-center text-sm text-[#81746B]">KhÃ´ng cÃ³ user phÃ¹ há»£p.</p>}<div className="flex items-center justify-between border-t border-[#2A2421] p-4 text-xs text-[#A69B93]">Trang {page}/{totalPages}<div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((v) => v - 1)} className="rounded-lg border border-[#3A302B] p-2 disabled:opacity-30"><ChevronLeft className="h-4 w-4" /></button><button disabled={page >= totalPages} onClick={() => setPage((v) => v + 1)} className="rounded-lg border border-[#3A302B] p-2 disabled:opacity-30"><ChevronRight className="h-4 w-4" /></button></div></div></section>;
}

