import type { Metadata } from "next";
import LegalPage from "../../../components/legal/LegalPage";
export const metadata: Metadata = { title: "Điều khoản sử dụng", description: "Điều khoản sử dụng website, tài khoản, mua hàng và dịch vụ TRIA CAFE." };
export default function TermsPage() { return <LegalPage eyebrow="Legal · TRIA CAFE" title="Điều khoản sử dụng" intro="Khi truy cập website, tạo tài khoản, đăng nội dung hoặc mua sản phẩm/dịch vụ của TRIA CAFE, bạn xác nhận đã đọc và đồng ý tuân thủ các điều khoản này." sections={[
 { title: "1. Phạm vi và chấp nhận điều khoản", paragraphs: ["Website triacafe.vn do TRIA CAFE vận hành để cung cấp thông tin thương hiệu, sản phẩm, cộng đồng, đặt lịch trải nghiệm và tiếp nhận nhu cầu hợp tác. TRIA có thể cập nhật điều khoản khi cần; phiên bản mới có hiệu lực từ thời điểm đăng tải."] },
 { title: "2. Tài khoản người dùng", paragraphs: ["Bạn chịu trách nhiệm cung cấp thông tin chính xác, bảo vệ mật khẩu và mọi hoạt động phát sinh từ tài khoản. Không được chia sẻ, mua bán, cho thuê tài khoản hoặc sử dụng tài khoản để mạo danh người khác."], bullets: ["Tài khoản phải sử dụng email/số điện thoại có quyền kiểm soát hợp pháp.", "TRIA có thể tạm khóa tài khoản khi phát hiện gian lận, spam, xâm phạm quyền người khác hoặc vi phạm pháp luật.", "Bạn có thể yêu cầu hỗ trợ khóa/xóa tài khoản qua hello@triacafe.vn."] },
 { title: "3. Sản phẩm, giá và đơn hàng", paragraphs: ["Thông tin giá, tồn kho, hình ảnh và mô tả được cập nhật theo từng thời điểm. Đơn hàng chỉ được xác nhận sau khi TRIA tiếp nhận và liên hệ xác nhận. Giá hiển thị có thể thay đổi trước thời điểm xác nhận đơn.", "Khách hàng không được sử dụng hệ thống để tạo đơn giả, khai thác lỗi giá, gian lận khuyến mại hoặc gây thiệt hại cho TRIA/đối tác vận chuyển."] },
 { title: "4. Sở hữu trí tuệ", paragraphs: ["Logo, tên thương hiệu, giao diện, nội dung, hình ảnh và tài liệu của TRIA CAFE thuộc TRIA hoặc bên cấp phép. Bạn không được sao chép, sửa đổi, phân phối, dùng thương mại hoặc đăng ký dấu hiệu gây nhầm lẫn nếu chưa có chấp thuận bằng văn bản."] },
 { title: "5. Giới hạn trách nhiệm", paragraphs: ["TRIA nỗ lực duy trì website an toàn và chính xác nhưng không cam kết dịch vụ luôn không gián đoạn hoặc không có lỗi. TRIA không chịu trách nhiệm cho thiệt hại phát sinh từ việc bạn cung cấp thông tin sai, làm lộ tài khoản, sử dụng dịch vụ trái phép hoặc sự cố ngoài khả năng kiểm soát hợp lý."] },
 { title: "6. Liên hệ và khiếu nại", paragraphs: ["Khiếu nại về đơn hàng, nội dung hoặc quyền lợi có thể gửi tới hello@triacafe.vn hoặc hotline 0989 668 113 / 0983 020 629. Vui lòng cung cấp URL, thời điểm và bằng chứng liên quan để TRIA xử lý nhanh hơn."] },
]} />; }
